"""Migration hints. A finding is a review prompt, never an automatic conversion."""

# id, severity, suggestion, confidence, explanation
RULES = {
    "read_csv": ("direct", "pl.read_csv(path)", "high", "Compare parser defaults, missing values and inferred types."),
    "read_parquet": ("direct", "pl.read_parquet(path)", "high", "Polars can read Parquet directly."),
    "read_json": ("rewrite", "pl.read_json(path)", "medium", "Check orientation and inferred types."),
    "read_excel": ("rewrite", "pl.read_excel(path)", "medium", "Check sheet selection and engine behavior."),
    "DataFrame": ("direct", "pl.DataFrame(data)", "high", "Check column types and row orientation."),
    "Series": ("rewrite", "pl.Series(name, values)", "medium", "Polars Series needs an explicit name in many uses."),
    "concat": ("rewrite", "pl.concat(frames, how='vertical')", "medium", "Choose a vertical or horizontal strategy explicitly."),
    "merge": ("rewrite", "left.join(right, on=keys, how='inner')", "medium", "Check null matching, suffixes and row order."),
    "to_datetime": ("rewrite", "pl.col(name).str.to_datetime()", "medium", "Parsing requires an expression and explicit timezone review."),
    "to_numeric": ("rewrite", "pl.col(name).cast(pl.Float64)", "medium", "Choose the intended numeric type and strictness."),
    "date_range": ("rewrite", "pl.date_range(start, end)", "medium", "Check interval and endpoint behavior."),
    "groupby": ("direct", "frame.group_by(keys).agg(...)", "medium", "Aggregation shape and ordering can differ."),
    "agg": ("rewrite", "frame.group_by(keys).agg(pl.col(name).sum())", "medium", "Translate aggregation names into expressions."),
    "sort_values": ("direct", "frame.sort(columns)", "medium", "Check null placement and stability."),
    "drop_duplicates": ("direct", "frame.unique(subset=columns)", "medium", "Check which duplicate row is retained."),
    "dropna": ("rewrite", "frame.drop_nulls()", "medium", "Pandas NaN and Polars null are distinct."),
    "fillna": ("rewrite", "frame.with_columns(pl.col(name).fill_null(value))", "medium", "Handle NaN separately if present."),
    "rename": ("direct", "frame.rename(mapping)", "medium", "Check axis and callback forms."),
    "query": ("rewrite", "frame.filter(pl.col(name) > value)", "medium", "Convert string expressions to Polars expressions."),
    "assign": ("rewrite", "frame.with_columns(expr.alias(name))", "medium", "Convert assignment callbacks to expressions."),
    "pivot_table": ("rewrite", "frame.pivot(on=column, index=keys, values=value)", "medium", "Check aggregation and duplicate keys."),
    "melt": ("rewrite", "frame.unpivot(on=columns, index=keys)", "medium", "Check output column names."),
    "resample": ("blocker", "frame.group_by_dynamic(index_column=timestamp, every=interval)", "high", "Requires sorted temporal data and explicit window semantics."),
    "apply": ("blocker", "Use native Polars expressions where possible", "high", "Python callbacks can prevent vectorized execution."),
    "iterrows": ("blocker", "Use expressions or iter_rows only at an external boundary", "high", "Row loops need a manual algorithm review."),
    "itertuples": ("blocker", "Use expressions or iter_rows only at an external boundary", "high", "Row loops need a manual algorithm review."),
    "set_index": ("blocker", "Keep keys as named columns", "high", "Polars has no implicit row index."),
    "reset_index": ("blocker", "Keep keys as named columns", "high", "Polars has no implicit row index."),
    "reindex": ("blocker", "Use an explicit key join", "high", "Polars has no implicit row index."),
    "MultiIndex": ("blocker", "Represent index levels as columns", "high", "Polars has no MultiIndex."),
    "loc": ("blocker", "Use filter and select with explicit columns", "medium", "Label-indexed slicing needs semantic review."),
    "iloc": ("rewrite", "Use slice or gather with explicit row positions", "medium", "Row positions need a deliberate ordering."),
    "at": ("blocker", "Use filter and select with explicit columns", "medium", "Scalar label indexing depends on an index."),
    "iat": ("rewrite", "Use explicit row and column selection", "medium", "Row positions need a deliberate ordering."),
    "astype": ("rewrite", "frame.with_columns(pl.col(name).cast(dtype))", "medium", "Pandas object dtype has no direct Polars equivalent."),
    "to_numpy": ("rewrite", "frame.to_numpy()", "medium", "Check null conversion and copies."),
    "to_pandas": ("rewrite", "Keep Polars data until an integration boundary", "medium", "Conversion may allocate and change null behavior."),
    "to_csv": ("direct", "frame.write_csv(path)", "medium", "Check index and header defaults."),
    "to_parquet": ("direct", "frame.write_parquet(path)", "medium", "Check compression defaults."),
    "dt_tz_localize": ("blocker", "Use dt.replace_time_zone and review ambiguous times", "high", "Timezone localization needs explicit ambiguity handling."),
    "dt_tz_convert": ("rewrite", "Use dt.convert_time_zone", "medium", "Check source timezone assumptions."),
    "cat": ("rewrite", "Use pl.Categorical and review string cache scope", "low", "Categorical identity differs across frames."),
}
WEIGHTS = {"direct": 0, "rewrite": 1, "blocker": 3}
